### ISSUE TITLE
Mollie assumes to be the only payment method for Sylius

### ISSUE THREAD

**Issue by ofinsterbusch** [mollie/Sylius#33]
When having multiple payment methods for different channels Mollie assumes it will be the main payment method. 

This affects the way the _SyliusMolliePlugin\Payments\MethodResolver\MolliePaymentMethodResolver_ class works

The resolvers checks for a Mollie payment method and then for it's parents but using the default payment method resolver and not the _ChannelBasedPaymentMethodResolver_. This results in showing any payment method that is enabled without considering the customer order channel. 

This can be solved decorating the service _sylius_mollie_plugin.payment_resolver.mollie_payment_method.inner_ and pointing it to the _ChannelBasedPaymentMethodResolver_

But it probably should go through all the methods in the CompositePaymentMethodResolver ignoring the mollie one.

**Comment by logeecom** [comment]
Hello @ofinsterbusch,

Thank you for reaching out.

We will check this and come back to you as soon as possible.

Thank you,

Kind regards.

**Comment by logeecom** [comment]
Hello @ofinsterbusch,

Note that our team finished investigating the reported issue.

When Sylius has more than 1 sales channels, all the payment methods from all channels will be shown on checkout for every channel.
![image-20241120-091701](https://github.com/user-attachments/assets/e8e644d0-506d-4e0a-a02f-975ee2ba929c)
The issue is caused as our MolliePaymentMethodResolver is being decorated with the default resolver, as already stated by you. Since there is no prebuilt channel-based resolver in Sylius, we fixed the issue by adding the method that filters payment methods per channel. Now, only payment methods that belong to certain channels will be shown for it on checkout.
![image-20241120-091946](https://github.com/user-attachments/assets/60e4848a-3a1b-4007-8ddc-db5337d76d52)
Please note that the changes will be live with the next release (expected at the start of the next week).

Thank you,

Kind regards.

**Comment by ofinsterbusch** [comment]
That's great, thank you!

**Comment by DamjanLogeecom** [comment]
Hello @ofinsterbusch,

Note that a new plugin version has been released. It can be found here: https://github.com/mollie/Sylius/releases/tag/v5.7.4 

Thank you,

Kind regards.

**Comment by logeecom** [comment]
Hello @ofinsterbusch,

Note that a new plugin version has been released. It can be found here: https://github.com/mollie/Sylius/releases/tag/v5.7.4 

Thank you,

Kind regards.
